= Выбор исполнителя группы заданий

В число исполнителей _Группы заданий_ могут входить Сотрудники, Подразделения, Группы, Роли _Справочника сотрудников_, поисковые слова. Данные категории будут доступны для выбора в карточке при соблюдении следующих условий:

* В _Справочнике сотрудников_ должны быть настроены указанные категории (созданы записи на сотрудников, имеются наполненные группы, подразделения, роли).
* В _Справочнике видов карточек_ должен быть определен список доступных исполнителей.

Список доступных поисковых слов для Группы заданий ограничен вариантами: _Все подчиненные_, _Заместители_, _Сотрудники департамента Автора_.

.Чтобы выбрать исполнителя при помощи быстрого поиска сотрудников, групп, подразделений, ролей и поисковых слов:
. Введите в строку быстрого поиска первые буквы имени. чтобы отобразить список всех подходящих вариантов.
+
. Добавьте результат в список выбранных исполнителей нажатием кнопки.
. Удалите ненужные записи нажатием на кнопку.
+
. Нажмите на кнопку или клавишу kbd:[Insert] на клавиатуре, чтобы выбрать исполнителя из доступных.
+
В появившемся окне _Справочника сотрудников_ можно не только выбрать существующую запись, но и создать новые или добавить сотрудников в созданный элемент. При выборе подразделения в таблице могут отображаться как название подразделения (в случае использования опции *_Подразделение_*), либо фамилии сотрудников подразделения (в случае использования опции *_Сотрудники_* с последующим выбором подразделения).
+
. Двойным щелчком мыши на записи выберите исполнителя.
+
Выбрать можно несколько исполнителей, а также выбор с использованием предопределенных поисковых слов и последних исполнителей.
+
. Чтобы выбрать из заранее сформированного списка исполнителей:
+
.. Нажмите на кнопку.
+
Использование данного способа (включая появление кнопки) определяется настройками вида Задания, указанного в настройках группы заданий в _Справочнике видов карточек_.
+
Будет открыто окно *Выбор исполнителя*.
+
.. Выбор производится двойным щелчком мыши на записи.
+
Допускается выбор нескольких исполнителей, а также выбор с использованием предопределенных поисковых слов и последних исполнителей.
+
Для каждого исполнителя по умолчанию указаны Имя и Вид.
+
. Для выбора сотрудников также можно использовать контекстные меню.
+
.. При вызове меню на пустой области таблицы доступны команды:
+
* добавить сотрудников;
* добавить подразделения;
* добавить группы;
* добавить роли.
.. При вызове меню на заполненной строке таблицы доступны команды:
* добавить сотрудников;
* добавить подразделения;
* добавить группы;
* добавить роли;
* изменить;
* удалить.
+
. В поле `Ответственный исполнитель` можно назначить одного из ранее выбранных исполнителей ответственным за выполнение группы заданий. Если в качестве исполнителя выбрана группа сотрудников, в поле `Ответственный` будут показаны сотрудники группы.
+
Сотрудник, назначенный ответственным, получит доступ к заданиям всех остальных исполнителей и, при необходимости, сможет завершить, отложить или изменить сроки выполнения задания.
