= Настройка контроля группы заданий

При отправке группы заданий исполнителям можно предусмотреть контроль выполнения заданий ответственным сотрудником. Настройка контроля различается в зависимости от выбранного варианта исполнения карточки.

Чтобы настроить контроль за выполнением группы заданий, выполните следующие действия:

. На вкладке *Основная* раскройте область *Приемка и контроль*.
. Установите флаг *На контроле*.
+
Станут доступными для заполнения поля *Дата контроля* и *Контролёр*.
. Выполните одно из доступных действий:
* если выбран вариант исполнения *Параллельно*, в поле *Дата контроля* укажите дату, когда должен быть выполнен контроль выполнения задания. Выбор даты можно произвести при помощи встроенного календаря, который открывается при нажатии на стрелку в правой части поля;
* если выбран вариант исполнения *Последовательно*, в поле *Контроль до завершения (ч.)* укажите количество часов, за которое должен быть выполнен контроль выполнения задания.
. В поле *Контролёр* укажите сотрудника, который будет контролировать качество выполнения задания. Выбор можно произвести из _Справочника сотрудников_, который открывается при нажатии на кнопку в правой части поля, либо при помощи быстрого поиска по подстроке.
+
Назначенный контролёр будет отображаться во всех запущенных заданиях.
+
Контролёр сможет осуществлять контроль выполнения заданий. Все завершенные задания сразу переходят в состояние _Завершено_ (и не переходят на приемку).

Если в карточке Группы заданий установлен флаг *На контроле*, то во всех заданиях группы в поля *Контролёр* и *Дата контроля* переносятся значения из соответствующих полей Группы заданий (при варианте исполнения *Последовательно* значение поля *Дата контроля* рассчитывается вычитанием значения поля *Контроль до завершения (ч.)* из значения поля *Дата завершения*).

Если в карточке одновременно установлены флаги *Требуется приемка* и *На контроле*:

* Если одновременно указаны Контролёр и Ответственный исполнитель, Контролёр будет проверять выполнение задания только Ответственного исполнителя. Задания остальных исполнителей на приёмку после завершения не переходят.
* Если указан только Контролёр, а Ответственный исполнитель -- нет, Контролёру на приемку переходят задания всех исполнителей.
