= Настройка приемки группы заданий

При отправке группы заданий исполнителям можно предусмотреть приемку заданий ответственным исполнителем. Настройка приемки различается в зависимости от выбранного варианта исполнения карточки.

Чтобы настроить приемку, выполните следующие действия:

. xref:task_GroupTask_create_performer.adoc[Укажите] Ответственного исполнителя.
. Раскройте область *Приемка и контроль*.
. Установите флаг *Требуется приемка*.
+
Все задания (кроме задания Ответственного исполнителя) в состоянии _На приемке_ будут переходить Ответственному исполнителю. При *Последовательном* варианте исполнения, пока предыдущее задание находится в состоянии _На приемке,_ следующее задание не будет выслано очередному исполнителю. Отправка произойдет только после перехода предыдущего задания в состояние _Завершено_.

Если в карточке установлен флаг *Требуется приемка*:

* если одновременно указаны Контролёр и Ответственный исполнитель, Контролёр будет проверять выполнение задания только Ответственного исполнителя. Задания остальных исполнителей на приёмку после завершения не переходят;
* если указан только Контролёр, а Ответственный исполнитель -- нет, Контролёру на приемку переходят задания всех исполнителей;
* если указан только Ответственный исполнитель, задания всех исполнителей (кроме своего собственного) переходят ему на приемку.

В экземплярах заданий, которые по завершении должны перейти в состояние _На приемке_, также автоматически устанавливается флаг *Требуется приемка*, а в поле *Контролёр* переносится значение либо из поля *Контролёр* (если он указан), либо из поля *Ответственный исполнитель* (если не указан Контролёр, но указан Ответственный исполнитель).
